### ISSUE TITLE
Failed to Deploy OPN 

### ISSUE THREAD

**Issue by munir94** [dmauser/opnazure#37] opened 2022-10-04 10:06 UTC
Hi , tried to deploy OPN using the Deploy to Azure Button but the template failed . Here is details 

Option : Single Nic
VNet range -172.16.16.0/20
Subnet - FIREWALL-SUBNET (/24)

![image](https://user-images.githubusercontent.com/39366930/195213538-ef990e2b-343c-48a7-b44d-4b6aacdc1f14.png)

{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
            {
                "code": "BadRequest",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidResourceReference\",\r\n    \"message\": \"Resource /subscriptions/xxx/rg/rgname/providers/Microsoft.Network/virtualNetworks/vnet/subnets/FIREWALL-SUBNET referenced by resource /subscriptions/xxxxx/resourceGroups/rg-name/providers/Microsoft.Network/networkInterfaces/OPNsense-Untrusted-NIC was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.\",\r\n    \"details\": []\r\n  }\r\n}"
            }
        ]
    }
}

**Comment by Welasco** [comment] 2022-10-04 13:46
@munir94, Unless you have a very specific test scenario/test to follow to be using SingleNic, I would change it for TwoNics. OPNSense was designed to have two nics, one external and one internal. Let me know if it works for you using TwoNics scenario.

I'll work on it to fix the SingleNic but it may take some time.

**Comment by Welasco** [comment] 2022-10-04 14:22
Hi @munir94, I was not able to reproduce the problem you have. I found a problem that when you use SingleNIC and let the form create a new vnet it fails. I'll fix it but it's not the same issue you referenced.

**Comment by Welasco** [comment] 2022-10-04 18:34
If fixed an issue regarding a trusted subnet deployment with a single nic scenario which was not required. I tested and it's working now. Once again I would encourage you to use TwoNics scenario instead.

Please let me know if you have any other questions.

**Comment by munir94** [comment] 2022-10-05 03:21
Hi @Welasco , i manage to deploy it with two nic option after a few attempts. last variable that i change is let vnet to locate in same rg with opn.

**Comment by cjnova** [comment] 2022-10-06 15:07
Hi @munir94 I reproduced your error deployment. You defined in the wizard FIREWALL-SUBNET as name for Untrusted-Subnet. Error shows that the deployment can't find it. Looking in the deployment I'm seeing Untrusted-Subnet instead FIREWALL-SUBNET.

![image](https://user-images.githubusercontent.com/43692126/194348501-a45cc5a7-a75d-4618-8726-04e6584f01f3.png)

This is the root-cause. If you try to deploy with `Untrusted-Subnet` as name it is going to work.

![image](https://user-images.githubusercontent.com/43692126/194349327-a723c37c-750b-428e-9dbe-3b7adf8e9ab0.png)

I'm going to look in the definition to see if it is hardcoded.

**Comment by cjnova** [comment] 2022-10-07 13:51
@munir94  I reviewed it. The assumption is to create a new VNET with subnets or to deploy in an existing one. So if you want to deploy on your own VNET subnet IP address and names, it is better to create them in advance and later run the deployment selecting them. If not the assumption is to create a new ones with default names in parameters.

@Welasco I think we can close the issue.

**Comment by pir8g33k** [comment] 2022-10-13 03:08
Hi Welasco is the deployment included azure log analytics?

**Comment by Welasco** [comment] 2023-02-15 23:41
@pir8g33k, Just closing the loop here.
Not it doesn't include Log Analytics.

**Closed as completed by Welasco** 2023-02-15 23:41 UTC
